version: "3.3"

services:
  web:
    build: .
    command: uvicorn apps.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/apps
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=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