version: "3.3"

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=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